### PR TITLE
add swedish

### PR DESCRIPTION
**Pull request by MrYakobo**
Based upon de.js, which uses prenoon and afternoon for AM/PM. Swedes use the 24-hour system and as such this seems reasonable.

### CODE REVIEW

**Comment by martinandert** [comment]
Hey Jakob, thanks for the translations! I'd like to merge it, however, can you please remove the package-lock.json file you've added? It's out of scope of the PR. Thanks!

**Comment by MrYakobo** [comment]
For sure :+1:

**Comment by martinandert** [comment]
I've just cut a new release with you additions. Thanks!

**Comment by MrYakobo** [comment]
Yo, I just realized I forgot to update the Readme (where it says the supported languages)

**Comment by martinandert** [comment]
> just realized I forgot to update the Readme

Just updated it. :smile:

**Pull request merged**
